-- migrate:up

CREATE TABLE workers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL UNIQUE,
  names VARCHAR(150) NOT NULL,
  last_names VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  document VARCHAR(50) NULL,
  phone VARCHAR(50) NULL,
  certification VARCHAR(255) NULL,
  position VARCHAR(100) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- migrate:down

DROP TABLE workers;