# tests/db/test_schema_from_plantuml.py
import pytest
from scripts.parse_plantuml import PlantUMLParser

class TestSchemaFromPlantUML:
  """Pruebas generadas automáticamente desde PlantUML"""
  
  @pytest.fixture(scope='class')
  def schema(self):
    """Carga el esquema desde PlantUML"""
    return PlantUMLParser('docs/db_diagram_sql.puml')
  
  def test_all_tables_exist(self, test_db, schema):
    """Verifica que todas las tablas del diagrama existan en la DB"""
    tables_in_uml = schema.get_all_tables()
    expected_tables = [
      'sexs', 'document_types', 'departments', 'provinces', 'districts',
      'persons', 'phones', 'addresses',
      'workers', 'students', 'representatives', 
      'representative_roles', 'representatives_students_roles',
      'levels', 'course_branches', 'courses', 'sections',
      'worker_roles', 'sections_workers_roles', 'sections_students',
      'folders', 'folder_common_materials', 'folder_section_materials',
      'documents', 'material_documents',
      'evaluation_types', 'section_evaluations', 'evaluation_documents',
      'section_evaluation_grades', 'section_evaluation_submissions',
      'submission_documents',
      'adverts'
    ]
    
    for table in expected_tables:
      test_db.execute(f"SHOW TABLES LIKE '{table}'")
      result = test_db.cursor.fetchone()
      assert result is not None, f"Tabla {table} no existe en la base de datos"
  
  def test_table_columns_match(self, test_db, schema):
    """Verifica que las columnas coincidan con el diagrama"""
    expected_columns = {
      'sexs': ['id', 'name'],
      'document_types': ['id', 'name'],
      'departments': ['id', 'name'],
      'provinces': ['id', 'name', 'department_id'],
      'districts': ['id', 'name', 'province_id'],
      'persons': ['id', 'names', 'lastNames', 'documentNumber', 'imageUrl', 
                  'birthDate', 'created', 'updated', 'sex_id', 'document_type_id'],
      'phones': ['id', 'person_id', 'description', 'phone'],
      'addresses': ['id', 'person_id', 'district_id', 'description', 'address'],
      'workers': ['id', 'code', 'bio', 'email', 'user_id', 'person_id'],
      'students': ['id', 'code', 'email', 'user_id', 'person_id'],
      'representatives': ['id', 'email', 'user_id', 'person_id'],
      'representative_roles': ['id', 'name'],
      'representatives_students_roles': ['id', 'representative_id', 'student_id', 
                                          'representative_role_id', 'created', 'updated'],
      'levels': ['id', 'name'],
      'course_branches': ['id', 'name'],
      'courses': ['id', 'name', 'code', 'description', 'sylabus_url', 
                  'level_id', 'branch_id', 'worker_id'],
      'sections': ['id', 'name', 'description', 'image_url', 'course_id'],
      'worker_roles': ['id', 'name'],
      'sections_workers_roles': ['id', 'section_id', 'worker_id', 'worker_role_id'],
      'sections_students': ['id', 'section_id', 'student_id'],
      'folders': ['id', 'parent_id', 'title', 'description', 'created', 'updated'],
      'folder_common_materials': ['id', 'course_id'],
      'folder_section_materials': ['id', 'section_id'],
      'documents': ['id', 'folder_id', 'title', 'autogenerated_title', 
                    'url', 'uploaded_by', 'created', 'updated'],
      'material_documents': ['id', 'material_id', 'document_id'],
      'evaluation_types': ['id', 'name', 'icon'],
      'section_evaluations': ['id', 'section_id', 'worker_id', 'evaluation_type_id',
                               'title', 'description', 'published_from', 'published_to',
                               'created', 'updated'],
      'evaluation_documents': ['id', 'section_evaluation_id', 'document_id'],
      'section_evaluation_grades': ['id', 'section_evaluation_id', 'student_id',
                                     'grade', 'feedback', 'created', 'updated'],
      'section_evaluation_submissions': ['id', 'section_evaluation_id', 'student_id',
                                          'created', 'updated'],
      'submission_documents': ['id', 'comment', 'submission_id', 'document_id'],
      'adverts': ['id', 'header', 'description', 'created', 'updated',
                  'published_from', 'published_to', 'visible', 'section_id', 'worker_id']
    }
    
    for table_name, columns in expected_columns.items():
      test_db.execute(f"SHOW COLUMNS FROM {table_name}")
      db_columns = [row['Field'] for row in test_db.cursor.fetchall()]
      
      for col in columns:
        assert col in db_columns, f"Columna {col} no existe en {table_name}"
  
  def test_pk_constraints(self, test_db, schema):
    """Verifica que las PK del diagrama estén definidas"""
    tables_with_pk = [
      'sexs', 'document_types', 'departments', 'provinces', 'districts',
      'persons', 'phones', 'addresses',
      'workers', 'students', 'representatives', 
      'representative_roles', 'representatives_students_roles',
      'levels', 'course_branches', 'courses', 'sections',
      'worker_roles', 'sections_workers_roles', 'sections_students',
      'folders', 'folder_common_materials', 'folder_section_materials',
      'documents', 'material_documents',
      'evaluation_types', 'section_evaluations', 'evaluation_documents',
      'section_evaluation_grades', 'section_evaluation_submissions',
      'submission_documents', 'adverts'
    ]
    
    for table_name in tables_with_pk:
      test_db.execute(f"SHOW KEYS FROM {table_name} WHERE Key_name = 'PRIMARY'")
      pk_in_db = test_db.cursor.fetchall()
      assert len(pk_in_db) >= 1, f"Tabla {table_name} no tiene PRIMARY KEY"