# sonar-project.properties
sonar.projectKey=classroom-app
sonar.projectName=Aula Virtual
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.exclusions=**/venv/**,**/tests/**,**/static/**,**/migrations/**,**/__pycache__/**,**/*.pyc

sonar.python.coverage.reportPaths=reports/coverage/coverage.xml

# Servidor (se puede sobreescribir desde línea de comandos)
sonar.host.url=http://localhost:9000